# Generated by Django 3.2.3 on 2021-05-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='doc_num',
            field=models.CharField(default='', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
